<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrsogaa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrsogaa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKrsogaa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKrsogaa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKrsogaa\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Krsogaa',
    'container.build_id' => '6e177a55',
    'container.build_time' => 1523256607,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrsogaa');
